robot:
  type: 'kuka'  # 'kuka', fr3
  pos: [0.0, -0.75, 0.5]
  joint_pos: [1.5, -0.1, 0.0, -1.6, 0.0, 1.6, 0.0]

patient:
  pos: [0.35, 0.15, 0.7]
  euler_yxz: [-90.0, 90.0, 0.0]
  id_list: ['s0015'] #['s0015', 's0024', 's0028', 's0029', 's0030'] # ['s0010'] # 's0010', 's0014', 's0015'
  label_res: 0.0015 # m
  target_anatomy: 'liver'

bed:
  pos: [0.0, 0.0, 0.3]
  euler_xyz: [90, 0.0, 90]
  scale: 0.001

motion_planning:
  patient_xz_goal: [200, 325, 0.0]
  use_vertebra_goal: False
  vertebra_to_US_2d_pos: [0.0, 0.0]
  scale: [[5, 5, 0.1]]
  max_roll_adj: 1

observation: 
  3D: False
  mode: 'seg' # 'seg', 'CT', 'US'
  scale: 1.0 # 0.02 for datacollection, 0.1 for learning-based
  scale_net: 0.1
action: 
  mode: 'continuous' # 'discrete', 'continuous'
  scale: [2, 2, 0.5,0.5] # [0.00002, 0.00002, 0.0001] # 
  max_action: [4, 4, 1, 1]

reward:
  w_pos: 0.03

sim:
  episode_length: 200
  patient_xz_range: [[50, 40, 0.5], [350, 380, 3.5]]
  patient_xz_init_range: [[180, 150, 0.5], [200, 200, 3.5]]
  if_use_ct: False
  ct_range: [-300, 3000]
  us: 'conv'
  vis_us: True
  vis_int: 20
  vis_seg_map: True


if_record_traj: True
record_path: /recordings/robot_US_guidance/
