seed: 42 # make training reproducible


# Models are instantiated using skrl's model instantiator utility
# https://skrl.readthedocs.io/en/latest/api/utils/model_instantiators.html
models:
  separate: False # actor and critic share the same CNN backbone if False
  policy:  # see gaussian_model parameters
    class: GaussianMixin # CategoricalMixin #probability distribution  over 4 actions, not a fixed action to allow exploration through randomness ( go 2mm-- with std 0.5> agent goes somewhere between 1.8 and 2.3)
    clip_actions: False # enforce limit for actions to avoid out of range exploration (e.g., due to high std)
    clip_log_std: True # to enforce log limits
    min_log_std: -20.0
    max_log_std: 2.0
    initial_log_std: 0.0 #early training high exploration, later training low exploration because agent becomes confident
    network:
      - name: features_extractor # shared CNN backbone to extract features from input states (e.g., images)
        input: STATES  # PyTorch NHWC -> NCHW 
        layers: #extract visual features 
          - conv2d: {out_channels: 32, kernel_size: 8, stride: 2, padding: 0}
          - conv2d: {out_channels: 64, kernel_size: 4, stride: 2, padding: 0}
          - conv2d: {out_channels: 64, kernel_size: 4, stride: 2, padding: 0}
          - conv2d: {out_channels: 64, kernel_size: 3, stride: 1, padding: 0}
          - flatten
        activations: relu
      - name: net
        input: features_extractor
        layers: [512, 256, 128]
        activations: elu
    output: ACTIONS
  value:  # see deterministic_model parameters #critic is deterministic because it only estimates the value of a state, no need for exploration
    class: DeterministicMixin # outputs a fixed value for each state
    clip_actions: False
    network:
      - name: features_extractor
        input: STATES  # PyTorch NHWC -> NCHW
        layers:
          - conv2d: {out_channels: 32, kernel_size: 8, stride: 2, padding: 0}
          - conv2d: {out_channels: 64, kernel_size: 4, stride: 2, padding: 0}
          - conv2d: {out_channels: 64, kernel_size: 4, stride: 2, padding: 0}
          - conv2d: {out_channels: 64, kernel_size: 3, stride: 1, padding: 0}
          - flatten
        activations: relu
      - name: net
        input: features_extractor
        layers: [512, 256, 128]
        activations: elu
    output: ONE # one value for each state


# Rollout memory
# https://skrl.readthedocs.io/en/latest/api/memories/random.html
memory:
  class: RandomMemory
  memory_size: -1  # automatically determined (same as agent:rollouts)


# PPO agent configuration (field names are from PPO_DEFAULT_CONFIG)
# https://skrl.readthedocs.io/en/latest/api/agents/ppo.html
agent:
  class: PPO
  rollouts: 32 # Collect 32 steps per environment before doing any update. With 64 envs → 32×64 = 2048 experience samples per update.
  mini_batches: 32
  discount_factor: 0.99
  lambda: 0.95
  learning_rate: 1.0e-04
  learning_rate_scheduler: KLAdaptiveLR
  learning_rate_scheduler_kwargs:
    kl_threshold: 0.008
  state_preprocessor: null
  state_preprocessor_kwargs: null
  value_preprocessor: RunningStandardScaler
  value_preprocessor_kwargs: null
  random_timesteps: 0
  learning_starts: 0
  grad_norm_clip: 1.0
  ratio_clip: 0.2
  value_clip: 0.2
  clip_predicted_values: True
  entropy_loss_scale: 0.0
  value_loss_scale: 1.0
  kl_threshold: 0.0
  rewards_shaper_scale: 1.0
  time_limit_bootstrap: False
  # logging and checkpoint
  experiment:
    directory: "US_guidance"
    experiment_name: "PPO_US"
    write_interval: 1000 #auto
    checkpoint_interval: 5000 # Model weights saved every 5000 timesteps → you can resume from any checkpoint



# Sequential trainer
# https://skrl.readthedocs.io/en/latest/api/trainers/sequential.html
trainer:
  class: SequentialTrainer
  timesteps: 500000
  environment_info: log
probe:   #i added this part
  type: convex          # <<< KEY
  #radius: 60             # mm, typical convex probe
  fan_angle: 60          # degrees (50–90 common)
  depth: 0.16            # mm (matches image height)

